
project_id = "ufqdgrceppavmdueczrg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[functions.process-payment]
verify_jwt = true

[functions.structure-medical-text]
verify_jwt = false

[functions.structure-medical-transcript]
verify_jwt = false

[functions.openai-structure-text]
verify_jwt = false
