// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufqdgrceppavmdueczrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcWRncmNlcHBhdm1kdWVjenJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODEzOTgsImV4cCI6MjA1Njk1NzM5OH0.5NxviWy0AlHgwsN9ovuy-4OrcgVHDpPHw5DnoLR1mNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);